#!/bin/ksh
source ./.apidays
apidays
ccloud
set -x
export CLUSTER_CLOUD=azure 
export CLUSTER_REGION=southeastasia
read Pause
set +x
yes y | confluent local destroy
cd examples-5.5.1-post/ccloud
chmod +x start.sh
yes y | ./start.sh
